### ISSUE TITLE
v3 13B exp4 (Sakura)

### ISSUE THREAD

**Issue by odashi** [llm-jp/experiments#1]
# Overview

v3 13Bモデルの事前学習を行います。

# Details

モデルカードPR: https://github.com/llm-jp/model-cards/pull/15
v2-v3 ablation studyなどを踏まえて設計したexp4実験の、さくらインターネットでの継続学習です。

# Resources

* **計算機**
  * クラスタ: Sakura (Ishikari)
  * ノード種別: gpu-small (H100x8)
  * ノード台数: <s>32</s> 16
* **コード**
  * リポジトリ: https://github.com/llm-jp/Megatron-LM/
  * コミット: [936f556](https://github.com/llm-jp/Megatron-LM/tree/936f55676ee8d8f329a3fe12f5c4e7fdc51b46f8)
* **入力データ**: 
  - LLM-jp v3.1 コーパス: `sakura:/data/llm-jp-corpus/v3.{0,1}.0`
* **出力データ**:
  - 保存先: `sakura:/data/experiments/1`
    - <s>速度問題が解決するまで `sakura:/home/odashi/experiments/1` を仮利用</s> 仮利用終了
  - データ内訳:
    - Megatron-LM checkpoint: 100TB 程度
* **W&B ログ**:
  * [W&B (GENIAC)](https://wandb.ai/nii-geniac/Llama-2-13B)
    * Tag: `main`, `exp4`
* **開始日**: 2024-07-27
* **終了予定日**: 2024-09-15

**Comment by odashi** [comment]
保存先は `sakura:/data/experiments/1` とします。

**Comment by YumaTsuta** [comment]
@odashi exp番号が違っていたので変更しました

**Comment by odashi** [comment]
学習開始したので諸元を更新しました。
GENIAC関係の要望で途中で一度ストップする可能性があります。

**Comment by odashi** [comment]
昨日checkpointを全て `/data` に移動しました。

**Comment by odashi** [comment]
チューニング実験との兼ね合いでノード数を16に減らしました。

**Comment by odashi** [comment]
学習完了しました。データを/dataに移動します。

**Comment by odashi** [comment]
データ移転とチェックサムの確認を終了しました。
