### ISSUE TITLE
v2-13b-expA-Pile

### ISSUE THREAD

**Issue by junjiechen-chris** [llm-jp/experiments#6]
# Overview

v2 13B モデル・v3コーパス（En=Pile)の事前学習

# Details

モデルカードPR: https://github.com/llm-jp/model-cards/pull/17

# Resources

* **計算機**
  * クラスタ: Sakura (Ishikari)
  * ノード種別: gpu-small (H100x8)
  * ノード台数: 8
* **コード**
  * リポジトリ: https://github.com/llm-jp/Megatron-LM
  * コミット: 402e6ff1
* **入力データ**:
  * v3.0 data (except dolma): `/data/llm-jp-corpus/v3.0.0/training_resharded_tokenize_ver2.2_code20K_en40K_ja60K.ver2.2`
  * Pile data:　`/data/llm-jp-corpus/v1.0.1/merge/binarized/ver2.2/code20K_en40K_ja60K`
* **出力データ**:
  * 保存先: `sakura:/data/experiments/6`
  * データ内訳:
    * {name}: xxx TB （バッファ容量を含む）
* **W&B ログ**:
  * [Training log](https://wandb.ai/llm-jp/13b-expA-Pile-sakura?nw=nwuserjunjiechen)
  * [Eval log](https://wandb.ai/llm-jp/test-llm-jp-eval-expA-Pile?nw=nwuserjunjiechen)
* **開始日**: 2024-07-27
* **終了予定日**: ~~2024-08-16 （バッファ期間を含む）~~

**Comment by junjiechen-chris** [comment]
一回目に訓練したexpA-Pileモデル（図１）が明らかにおかしいので、再訓練を行いました。
結果、自然言語らしきものが生成されましたが、llm-jp-eval v1.3.1において、5000 iterationまでの結果が0.5以下でした（図２）。ほかのモデルとの差が大きいと改善する見込みがないため、今回の訓練を中止しようと思います。
今回の結果はだいぶおかしいので、何回もスクリプトの検査をしましたが、データセットをen_pileに置き換えた以外、全てが一致しています。問題を探し出すために、expAの訓練を5000iterationぐらいやってみたいです。（ablation sheetに5000 itの性能があります）
![image](https://github.com/user-attachments/assets/071414ab-5525-4a11-b0f4-bfdac2e83919)
![image](https://github.com/user-attachments/assets/d5122aad-c5ed-460f-8f4a-fac2fe087542)

**Comment by odashi** [comment]
ありがとうございます。最終的なデータ容量を更新して、こちらのissueをcloseして下さい。
しかし性能差は謎ですね…

**Comment by junjiechen-chris** [comment]
ありがとうございます。
checkpointsは`/home/shared/experiments/6/checkpoints`に入れました

> しかし性能差は謎ですね…
そうですね、自分も明かしておきたいですが、現状ノード使用予定を見ますと、これを後伸ばしようと思います。
